### ISSUE TITLE
DHCP test errors on raspiberrypi

### ISSUE THREAD

**Issue by benroeder** [wifinigel/wiperf#39]
I enable DHCP testing and I get these errors, is this an issue as it seems to log the DHCP response metric
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.7/logging/handlers.py", line 68, in emit
    if self.shouldRollover(record):
  File "/usr/lib/python3.7/logging/handlers.py", line 184, in shouldRollover
    msg = "%s\n" % self.format(record)
  File "/usr/lib/python3.7/logging/__init__.py", line 880, in format
    return fmt.format(record)
  File "/usr/lib/python3.7/logging/__init__.py", line 619, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.7/logging/__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/share/wiperf/wiperf_run.py", line 7, in <module>
    agent.run()
  File "/usr/local/lib/python3.7/dist-packages/wiperf_poller/__main__.py", line 366, in run
    main()
  File "/usr/local/lib/python3.7/dist-packages/wiperf_poller/__main__.py", line 329, in main
    tests_passed = dhcp_obj.run_tests(status_file_obj, config_vars, exporter_obj)
  File "/usr/local/lib/python3.7/dist-packages/wiperf_poller/testers/dhcptester.py", line 107, in run_tests
    renewal_result = self.dhcp_renewal(interface, mode=config_vars['dhcp_test_mode'])
  File "/usr/local/lib/python3.7/dist-packages/wiperf_poller/testers/dhcptester.py", line 64, in dhcp_renewal
    self.file_logger.debug("dhcp:", line.rstrip())
Message: 'dhcp:'
Arguments: (b'Internet Systems Consortium DHCP Client 4.4.1',)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.7/logging/handlers.py", line 68, in emit
    if self.shouldRollover(record):
  File "/usr/lib/python3.7/logging/handlers.py", line 184, in shouldRollover
    msg = "%s\n" % self.format(record)
  File "/usr/lib/python3.7/logging/__init__.py", line 880, in format
    return fmt.format(record)
  File "/usr/lib/python3.7/logging/__init__.py", line 619, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.7/logging/__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/share/wiperf/wiperf_run.py", line 7, in <module>
    agent.run()
  File "/usr/local/lib/python3.7/dist-packages/wiperf_poller/__main__.py", line 366, in run
    main()
  File "/usr/local/lib/python3.7/dist-packages/wiperf_poller/__main__.py", line 329, in main
    tests_passed = dhcp_obj.run_tests(status_file_obj, config_vars, exporter_obj)
  File "/usr/local/lib/python3.7/dist-packages/wiperf_poller/testers/dhcptester.py", line 107, in run_tests
    renewal_result = self.dhcp_renewal(interface, mode=config_vars['dhcp_test_mode'])
  File "/usr/local/lib/python3.7/dist-packages/wiperf_poller/testers/dhcptester.py", line 64, in dhcp_renewal
    self.file_logger.debug("dhcp:", line.rstrip())
Message: 'dhcp:'
Arguments: (b'Copyright 2004-2018 Internet Systems Consortium.',)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.7/logging/handlers.py", line 68, in emit
    if self.shouldRollover(record):
  File "/usr/lib/python3.7/logging/handlers.py", line 184, in shouldRollover
    msg = "%s\n" % self.format(record)
  File "/usr/lib/python3.7/logging/__init__.py", line 880, in format
    return fmt.format(record)
  File "/usr/lib/python3.7/logging/__init__.py", line 619, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.7/logging/__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/share/wiperf/wiperf_run.py", line 7, in <module>
    agent.run()
  File "/usr/local/lib/python3.7/dist-packages/wiperf_poller/__main__.py", line 366, in run
    main()
  File "/usr/local/lib/python3.7/dist-packages/wiperf_poller/__main__.py", line 329, in main
    tests_passed = dhcp_obj.run_tests(status_file_obj, config_vars, exporter_obj)
  File "/usr/local/lib/python3.7/dist-packages/wiperf_poller/testers/dhcptester.py", line 107, in run_tests
    renewal_result = self.dhcp_renewal(interface, mode=config_vars['dhcp_test_mode'])
  File "/usr/local/lib/python3.7/dist-packages/wiperf_poller/testers/dhcptester.py", line 64, in dhcp_renewal
    self.file_logger.debug("dhcp:", line.rstrip())
Message: 'dhcp:'
Arguments: (b'All rights reserved.',)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.7/logging/handlers.py", line 68, in emit
    if self.shouldRollover(record):
  File "/usr/lib/python3.7/logging/handlers.py", line 184, in shouldRollover
    msg = "%s\n" % self.format(record)
  File "/usr/lib/python3.7/logging/__init__.py", line 880, in format
    return fmt.format(record)
  File "/usr/lib/python3.7/logging/__init__.py", line 619, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.7/logging/__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/share/wiperf/wiperf_run.py", line 7, in <module>
    agent.run()
  File "/usr/local/lib/python3.7/dist-packages/wiperf_poller/__main__.py", line 366, in run
    main()
  File "/usr/local/lib/python3.7/dist-packages/wiperf_poller/__main__.py", line 329, in main
    tests_passed = dhcp_obj.run_tests(status_file_obj, config_vars, exporter_obj)
  File "/usr/local/lib/python3.7/dist-packages/wiperf_poller/testers/dhcptester.py", line 107, in run_tests
    renewal_result = self.dhcp_renewal(interface, mode=config_vars['dhcp_test_mode'])
  File "/usr/local/lib/python3.7/dist-packages/wiperf_poller/testers/dhcptester.py", line 64, in dhcp_renewal
    self.file_logger.debug("dhcp:", line.rstrip())
Message: 'dhcp:'
Arguments: (b'For info, please visit https://www.isc.org/software/dhcp/',)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.7/logging/handlers.py", line 68, in emit
    if self.shouldRollover(record):
  File "/usr/lib/python3.7/logging/handlers.py", line 184, in shouldRollover
    msg = "%s\n" % self.format(record)
  File "/usr/lib/python3.7/logging/__init__.py", line 880, in format
    return fmt.format(record)
  File "/usr/lib/python3.7/logging/__init__.py", line 619, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.7/logging/__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/share/wiperf/wiperf_run.py", line 7, in <module>
    agent.run()
  File "/usr/local/lib/python3.7/dist-packages/wiperf_poller/__main__.py", line 366, in run
    main()
  File "/usr/local/lib/python3.7/dist-packages/wiperf_poller/__main__.py", line 329, in main
    tests_passed = dhcp_obj.run_tests(status_file_obj, config_vars, exporter_obj)
  File "/usr/local/lib/python3.7/dist-packages/wiperf_poller/testers/dhcptester.py", line 107, in run_tests
    renewal_result = self.dhcp_renewal(interface, mode=config_vars['dhcp_test_mode'])
  File "/usr/local/lib/python3.7/dist-packages/wiperf_poller/testers/dhcptester.py", line 64, in dhcp_renewal
    self.file_logger.debug("dhcp:", line.rstrip())
Message: 'dhcp:'
Arguments: (b'',)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.7/logging/handlers.py", line 68, in emit
    if self.shouldRollover(record):
  File "/usr/lib/python3.7/logging/handlers.py", line 184, in shouldRollover
    msg = "%s\n" % self.format(record)
  File "/usr/lib/python3.7/logging/__init__.py", line 880, in format
    return fmt.format(record)
  File "/usr/lib/python3.7/logging/__init__.py", line 619, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.7/logging/__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/share/wiperf/wiperf_run.py", line 7, in <module>
    agent.run()
  File "/usr/local/lib/python3.7/dist-packages/wiperf_poller/__main__.py", line 366, in run
    main()
  File "/usr/local/lib/python3.7/dist-packages/wiperf_poller/__main__.py", line 329, in main
    tests_passed = dhcp_obj.run_tests(status_file_obj, config_vars, exporter_obj)
  File "/usr/local/lib/python3.7/dist-packages/wiperf_poller/testers/dhcptester.py", line 107, in run_tests
    renewal_result = self.dhcp_renewal(interface, mode=config_vars['dhcp_test_mode'])
  File "/usr/local/lib/python3.7/dist-packages/wiperf_poller/testers/dhcptester.py", line 64, in dhcp_renewal
    self.file_logger.debug("dhcp:", line.rstrip())
Message: 'dhcp:'
Arguments: (b'Listening on LPF/wlan0/dc:a6:32:e4:0b:7b',)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.7/logging/handlers.py", line 68, in emit
    if self.shouldRollover(record):
  File "/usr/lib/python3.7/logging/handlers.py", line 184, in shouldRollover
    msg = "%s\n" % self.format(record)
  File "/usr/lib/python3.7/logging/__init__.py", line 880, in format
    return fmt.format(record)
  File "/usr/lib/python3.7/logging/__init__.py", line 619, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.7/logging/__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/share/wiperf/wiperf_run.py", line 7, in <module>
    agent.run()
  File "/usr/local/lib/python3.7/dist-packages/wiperf_poller/__main__.py", line 366, in run
    main()
  File "/usr/local/lib/python3.7/dist-packages/wiperf_poller/__main__.py", line 329, in main
    tests_passed = dhcp_obj.run_tests(status_file_obj, config_vars, exporter_obj)
  File "/usr/local/lib/python3.7/dist-packages/wiperf_poller/testers/dhcptester.py", line 107, in run_tests
    renewal_result = self.dhcp_renewal(interface, mode=config_vars['dhcp_test_mode'])
  File "/usr/local/lib/python3.7/dist-packages/wiperf_poller/testers/dhcptester.py", line 64, in dhcp_renewal
    self.file_logger.debug("dhcp:", line.rstrip())
Message: 'dhcp:'
Arguments: (b'Sending on   LPF/wlan0/dc:a6:32:e4:0b:7b',)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.7/logging/handlers.py", line 68, in emit
    if self.shouldRollover(record):
  File "/usr/lib/python3.7/logging/handlers.py", line 184, in shouldRollover
    msg = "%s\n" % self.format(record)
  File "/usr/lib/python3.7/logging/__init__.py", line 880, in format
    return fmt.format(record)
  File "/usr/lib/python3.7/logging/__init__.py", line 619, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.7/logging/__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/share/wiperf/wiperf_run.py", line 7, in <module>
    agent.run()
  File "/usr/local/lib/python3.7/dist-packages/wiperf_poller/__main__.py", line 366, in run
    main()
  File "/usr/local/lib/python3.7/dist-packages/wiperf_poller/__main__.py", line 329, in main
    tests_passed = dhcp_obj.run_tests(status_file_obj, config_vars, exporter_obj)
  File "/usr/local/lib/python3.7/dist-packages/wiperf_poller/testers/dhcptester.py", line 107, in run_tests
    renewal_result = self.dhcp_renewal(interface, mode=config_vars['dhcp_test_mode'])
  File "/usr/local/lib/python3.7/dist-packages/wiperf_poller/testers/dhcptester.py", line 64, in dhcp_renewal
    self.file_logger.debug("dhcp:", line.rstrip())
Message: 'dhcp:'
Arguments: (b'Sending on   Socket/fallback',)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.7/logging/handlers.py", line 68, in emit
    if self.shouldRollover(record):
  File "/usr/lib/python3.7/logging/handlers.py", line 184, in shouldRollover
    msg = "%s\n" % self.format(record)
  File "/usr/lib/python3.7/logging/__init__.py", line 880, in format
    return fmt.format(record)
  File "/usr/lib/python3.7/logging/__init__.py", line 619, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.7/logging/__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/share/wiperf/wiperf_run.py", line 7, in <module>
    agent.run()
  File "/usr/local/lib/python3.7/dist-packages/wiperf_poller/__main__.py", line 366, in run
    main()
  File "/usr/local/lib/python3.7/dist-packages/wiperf_poller/__main__.py", line 329, in main
    tests_passed = dhcp_obj.run_tests(status_file_obj, config_vars, exporter_obj)
  File "/usr/local/lib/python3.7/dist-packages/wiperf_poller/testers/dhcptester.py", line 107, in run_tests
    renewal_result = self.dhcp_renewal(interface, mode=config_vars['dhcp_test_mode'])
  File "/usr/local/lib/python3.7/dist-packages/wiperf_poller/testers/dhcptester.py", line 64, in dhcp_renewal
    self.file_logger.debug("dhcp:", line.rstrip())
Message: 'dhcp:'
Arguments: (b'DHCPDISCOVER on wlan0 to 255.255.255.255 port 67 interval 6',)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.7/logging/handlers.py", line 68, in emit
    if self.shouldRollover(record):
  File "/usr/lib/python3.7/logging/handlers.py", line 184, in shouldRollover
    msg = "%s\n" % self.format(record)
  File "/usr/lib/python3.7/logging/__init__.py", line 880, in format
    return fmt.format(record)
  File "/usr/lib/python3.7/logging/__init__.py", line 619, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.7/logging/__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/share/wiperf/wiperf_run.py", line 7, in <module>
    agent.run()
  File "/usr/local/lib/python3.7/dist-packages/wiperf_poller/__main__.py", line 366, in run
    main()
  File "/usr/local/lib/python3.7/dist-packages/wiperf_poller/__main__.py", line 329, in main
    tests_passed = dhcp_obj.run_tests(status_file_obj, config_vars, exporter_obj)
  File "/usr/local/lib/python3.7/dist-packages/wiperf_poller/testers/dhcptester.py", line 107, in run_tests
    renewal_result = self.dhcp_renewal(interface, mode=config_vars['dhcp_test_mode'])
  File "/usr/local/lib/python3.7/dist-packages/wiperf_poller/testers/dhcptester.py", line 64, in dhcp_renewal
    self.file_logger.debug("dhcp:", line.rstrip())
Message: 'dhcp:'
Arguments: (b'DHCPOFFER of 192.168.1.101 from 192.168.1.1',)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.7/logging/handlers.py", line 68, in emit
    if self.shouldRollover(record):
  File "/usr/lib/python3.7/logging/handlers.py", line 184, in shouldRollover
    msg = "%s\n" % self.format(record)
  File "/usr/lib/python3.7/logging/__init__.py", line 880, in format
    return fmt.format(record)
  File "/usr/lib/python3.7/logging/__init__.py", line 619, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.7/logging/__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/share/wiperf/wiperf_run.py", line 7, in <module>
    agent.run()
  File "/usr/local/lib/python3.7/dist-packages/wiperf_poller/__main__.py", line 366, in run
    main()
  File "/usr/local/lib/python3.7/dist-packages/wiperf_poller/__main__.py", line 329, in main
    tests_passed = dhcp_obj.run_tests(status_file_obj, config_vars, exporter_obj)
  File "/usr/local/lib/python3.7/dist-packages/wiperf_poller/testers/dhcptester.py", line 107, in run_tests
    renewal_result = self.dhcp_renewal(interface, mode=config_vars['dhcp_test_mode'])
  File "/usr/local/lib/python3.7/dist-packages/wiperf_poller/testers/dhcptester.py", line 64, in dhcp_renewal
    self.file_logger.debug("dhcp:", line.rstrip())
Message: 'dhcp:'
Arguments: (b'DHCPREQUEST for 192.168.1.101 on wlan0 to 255.255.255.255 port 67',)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.7/logging/handlers.py", line 68, in emit
    if self.shouldRollover(record):
  File "/usr/lib/python3.7/logging/handlers.py", line 184, in shouldRollover
    msg = "%s\n" % self.format(record)
  File "/usr/lib/python3.7/logging/__init__.py", line 880, in format
    return fmt.format(record)
  File "/usr/lib/python3.7/logging/__init__.py", line 619, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.7/logging/__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/share/wiperf/wiperf_run.py", line 7, in <module>
    agent.run()
  File "/usr/local/lib/python3.7/dist-packages/wiperf_poller/__main__.py", line 366, in run
    main()
  File "/usr/local/lib/python3.7/dist-packages/wiperf_poller/__main__.py", line 329, in main
    tests_passed = dhcp_obj.run_tests(status_file_obj, config_vars, exporter_obj)
  File "/usr/local/lib/python3.7/dist-packages/wiperf_poller/testers/dhcptester.py", line 107, in run_tests
    renewal_result = self.dhcp_renewal(interface, mode=config_vars['dhcp_test_mode'])
  File "/usr/local/lib/python3.7/dist-packages/wiperf_poller/testers/dhcptester.py", line 64, in dhcp_renewal
    self.file_logger.debug("dhcp:", line.rstrip())
Message: 'dhcp:'
Arguments: (b'DHCPACK of 192.168.1.101 from 192.168.1.1',)

**Comment by wifinigel** [comment]
Hi Ben,

This looks like a type error in the logging that needs fixing. If you disable debug mode, it will likely go away. I'll add it to the list of things to fix in the next update.

The debugging is very verbose and mainly intended for development work. I'd turn it off for normal day to day operation to make sure it doesn't cause any performance issues for wiperf.

Thanks for the report! 👍 

Nigel.

**Comment by wifinigel** [comment]
Type error fixed and committed to v2.1 dev code.
